### ISSUE TITLE
Project seed doesn't start.

### ISSUE THREAD

**Issue by balazs-edes-lab49** [openfin/platform-api-project-seed#44]
I performed the following steps:
- forked the repo (as I'm intending to use it for a separate bug report)
- `npm ci` - so I keep using your original `package-lock.json`
- `npm start`

This is what I get:

```
balazs.edes@C02FFKLMMD6M platform-api-project-seed % npm start

> openfin-template@0.0.0 start /Users/balazs.edes/code/platform-api-project-seed
> node server.js

Launching application from: http://localhost:5555/app.json
(node:53715) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
(Use `node --trace-deprecation ...` to show where the warning was created)
Failed to launch
 Error: Could not resolve runtime version
    at Object.resolveRuntimeVersion (/Users/balazs.edes/code/platform-api-project-seed/node_modules/hadouken-js-adapter/src/launcher/util.js:75:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async install (/Users/balazs.edes/code/platform-api-project-seed/node_modules/hadouken-js-adapter/src/launcher/nix-launch.js:42:21)
    at async Object.launch [as default] (/Users/balazs.edes/code/platform-api-project-seed/node_modules/hadouken-js-adapter/src/launcher/nix-launch.js:69:29)
    at async /Users/balazs.edes/code/platform-api-project-seed/node_modules/hadouken-js-adapter/src/transport/port-discovery.js:151:37
    at async PortDiscovery.retrievePort (/Users/balazs.edes/code/platform-api-project-seed/node_modules/hadouken-js-adapter/src/transport/port-discovery.js:149:25)
    at async /Users/balazs.edes/code/platform-api-project-seed/server.js:40:22
Error: Could not resolve runtime version
    at Object.resolveRuntimeVersion (/Users/balazs.edes/code/platform-api-project-seed/node_modules/hadouken-js-adapter/src/launcher/util.js:75:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async install (/Users/balazs.edes/code/platform-api-project-seed/node_modules/hadouken-js-adapter/src/launcher/nix-launch.js:42:21)
    at async Object.launch [as default] (/Users/balazs.edes/code/platform-api-project-seed/node_modules/hadouken-js-adapter/src/launcher/nix-launch.js:69:29)
    at async /Users/balazs.edes/code/platform-api-project-seed/node_modules/hadouken-js-adapter/src/transport/port-discovery.js:151:37
    at async PortDiscovery.retrievePort (/Users/balazs.edes/code/platform-api-project-seed/node_modules/hadouken-js-adapter/src/transport/port-discovery.js:149:25)
    at async /Users/balazs.edes/code/platform-api-project-seed/server.js:40:22
```

Could you give me any hints what's missing?

**Comment by balazs-edes-lab49** [comment]
False alarm, company network policies.
